use filosofia;
create table filosofos(
filosofo_id int not null auto_increment primary key,
nombre_reconocido varchar(50),
nombre varchar(50) not null,
ciudad varchar(50),
anio varchar(25),
muerte varchar(25) default 'Desconocido',
periodo varchar(50)
);

insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Tales de Mileto', 'Tales', 'Mileto, Jonia', '624 a.C', '546 a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Anaximandro', 'Anaximandro', 'Mileto, Jonia', '610 a.C', '545 a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Anaxímenes', 'Anaxímenes', 'Mileto, Jonia', '590 a.C', '525 a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Pitágoras de Samos', 'Pitágoras', 'Samos, Antigua Grecia', '569 a.C', '475 a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Heráclito de Éfeso','Heráclito', 'Éfeso, Turquía', '540 a.C', '480 a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Parménides de Elea','Parménides', 'Elea, Magna Grecia (Italia)', 'Entre 515 y 530 a.C', 'Desconocido', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Empédocles de Agrigento','Empédocles', 'Agrigento, Magna Grecia (Italia)', '495 a.C', '444 a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Anaxágoras', 'Anaxágoras', 'Clazomene, Antigua Grecia', '500 a.C', '428 a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Sócrates', 'Sócrates', 'Alopece, Antigua Atenas', '470 a.C', '399 a.C.', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Demócrito de Abdera', 'Demócrito', 'Abdera, Tracia (Grecia)', '460 a.C', '370 a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Platón', 'Platón', 'Atenas, Antigua Atenas', '427 a.C', '347 a.C.', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Diógenes de Sinope', 'Diógenes', 'Sinope, Jonia', '412 a.C', '323 a.C.', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Aristóteles', 'Aristóteles', 'Estagira, Reino de Macedonia', '384 a.C', '322 a.C.', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Epicuro de Samos', 'Epicuro', 'Samos, Antigua Grecia', '341 a.C', '270 a.C.', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Zenón de Citio', 'Zenón', 'Citio, Chipre', '333 a.C', '264 a.C.', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Cicerón', 'Marco Tulio Cicerón', 'Arpino, Lacio (Italia)', '106 a.C', '43 a.C.', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Séneca', 'Lucio Anneo Séneca', 'Corduba, Bética', '4 a.C', '65', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Epicteto', 'Epicteto', 'Hierápolis, Actual Turquía', '55', '135', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Marco Aurelio', 'Marco Aurelio Antonino', 'Roma, Italia', '121', '180', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Plotino', 'Plotino', 'Lycopolis, Antiguo Egipto', '204', '270', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Agustín de Hipona', 'San Agustín', 'Tagaste, Imperio Romano', '354', '430', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Anselmo de Canterbury', 'Anselmo', 'Aosta, Alpes italianos', '1033', '1109', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Averroes', 'Averroes', 'Córdoba, Imperio Almorávide', '1126', '1198', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Santo Tomás de Aquino', 'Tomás de Aquino', 'Roccasecca, Reino de Sicilia', '1224', '1274', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Maestro Eckhart', 'Eckhart', 'Hochheim, Sacro Imperio Romano Germánico', '1260', '1328', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Guillermo de Ockham', 'Guillermo', 'Ockham, Surrey, Inglaterra', '1288', '1349', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Nicolás Maquiavelo', 'Nicolás Maquiavelo', 'Florencia, República de Florencia', '1469', '1527', 'Era de la Razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Erasmo de Róterdam', 'Erasmo', 'Róterdam, Diecisiete Provincias', '1466', '1536', 'Era de la Razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Martín Lutero', 'Martín Lutero', 'Eisleben, Sacro Imperio Romano Germánico', '1483', '1546', 'Era de la Razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Francisco de Vitoria', 'Francisco de Vitoria', 'Burgos, España', '1486', '1546', 'Era de la Razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Juan Calvino', 'Juan Calvino', 'Noyon, Francia', '1509', '1564', 'Era de la Razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Bartolomé de las Casas', 'Bartolomé de las Casas', 'Sevilla, España', '1484', '1566', 'Era de la Razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Francis Bacon', 'Francis Bacon', 'York House, Strand (Reino Unido)', '1561', '1626', 'Era de la Razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Galileo Galilei', 'Galileo Galilei', 'Pisa, Toscana, Italia', '1564', '1642', 'Era de la Razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('René Descartes', 'René Descartes', 'La Haye en Touraine, Francia', '1596', '1650', 'Era de la Razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Baruch Spinoza', 'Baruch Spinoza', 'Ámsterdam, Provincias Unidas de los Países Bajos', '1632', '1677', 'Era de la Razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Thomas Hobbes', 'Thomas Hobbes', 'Westport, Inglaterra', '1588', '1679', 'Era de la Razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('John Locke', 'John Locke', 'Wrington, Somerset, Reino de Inglaterra', '1632', '1704', 'Era de la Razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Gottfried Leibniz', 'Gottfried Wilhelm Leibniz', 'Leipzig, Electorado de Sajonia', '1646', '1716', 'Era de la Razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Isaac Newton', 'Isaac Newton', 'Woolsthorpe Manor, Inglaterra', '1642', '1727', 'Era de la Razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Montesquieu', 'Charles Louis de Secondat', 'La Brède, Francia', '1689', '1755', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('David Hume', 'David Hume', 'Edimburgo, Reino de Gran Bretaña', '1711', '1776', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Jean-Jacques Rousseau', 'Jean-Jacques Rousseau', 'Ginebra, Antigua Confederación Suiza', '1712', '1778', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Voltaire', 'François-Marie Arouet', 'París, Reino de Francia', '1694', '1778', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Adam Smith', 'Adam Smith', 'Kirkcaldy, Escocia, Reino de Gran Bretaña', '1723', '1790', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Immanuel Kant', 'Immanuel Kant', 'Königsberg, Prusia', '1724', '1804', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Georg Hegel', 'Georg Wilhelm Friedrich Hegel', 'Stuttgart, Ducado de Wurtemberg', '1770', '1831', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Arthur Schopenhauer', 'Arthur Schopenhauer', 'Gdansk, República de las Dos Naciones', '1788', '1860', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Karl Marx', 'Karl Heinrich Marx', 'Tréveris, Reino de Prusia', '1818', '1883', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Friedrich Nietzsche', 'Friedrich Wilhelm Nietzsche', 'Röcken, Prusia', '1844', '1900', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Henri Poincaré', 'Jules Henri Poincaré', 'Nancy, Meurthe-et-Moselle', '1854', '1912', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Max Weber', 'Maximilian Karl Emil Weber', 'Érfurt, Prusia', '1864', '1920', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Antonio Gramsci', 'Antonio Gramsci', 'Ales, Reino de Italia', '1891', '1937', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Bertrand Russell', 'Bertrand Arthur William Russell', 'Trellech, Monmouthshire, Gales, Reino Unido', '1872', '1970', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Jean-Paul Sartre', 'Jean-Paul Charles Aymard Sartre', 'París, Francia', '1905', '1980', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Michel Foucault', 'Paul-Michel Foucault', 'Poitiers, Vienne, Francia', '1926', '1984', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Leucipo de Mileto', 'Leucipo', 'Mileto, Jonia', 'Siglo V a.C.', 'Siglo V a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Giordano Bruno', 'Giordano Bruno', 'Nola, Reino de Nápoles, Monarquía Hispánica', '1548', '1600', 'Era de la razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Nicolaus de Autricuía', 'Nicolaus de Autricuria', 'Autrécourt-sur-Aire, Lorena, Francia', '1299', '1369', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Nicolás de Cusa', 'Nicolaus von Kues', 'Cusa, Tréveris', '1401', '1464', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Pierre Gassendi', 'Pierre Gassendi', 'Champtercier, Francia', '1592', '1655', 'Era de la razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Protágoras de Abdera', 'Protágoras', 'Abdera, Antigua Grecia', '481 a.C.', '411 a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Gorgias', 'Gorgias', 'Leontinos, Italia', '460 a.C.', '380 a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Hipias de Élide', 'Hipias de Élide', 'Elis, Grecia', '443 a.C.', '399 a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Pródico de Ceos', 'Pródico de Ceos', 'Yulis, Ceos, Antigua Grecia', '465 a.C.', '395 a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Antifonte de Atenas', 'Antifonte', 'Atenas, Antigua Grecia', '480 a.C.', '411 a.C.', '');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Critias', 'Critias', 'Antigua Atenas', '460 a.C.', '403 a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Trasímaco', 'Trasímaco', 'Calcedonia, Antigua Grecia', '459 a.C.', '400 a.C.', '');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Mario Victorino', 'Caius Marius Victorinus', 'África, Antigua Roma', '290', '364', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Boecio', 'Anicio Manlio Torcuato Severino Boecio', 'Roma (Reino de Odoacro)', '480', '524', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Isidoro de Sevilla', 'Isidoro de Sevilla', 'Sevilla', '560', '636', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Juan Escoto Erígena', 'Juan Escoto Erígena', 'Isla de Irlanda', '810', '877', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Justino Mártir', 'Justino Mártir', 'Flavia Neapolis, Siria', '100', '162', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Clemente de Alejandría', 'Clemente de Alejandría', 'Atenas, Grecia', '150', '215', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Orígenes de Alejandría', 'Orígenes', 'Alejandría, Egipto', '184', '253', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Ireneo de Lyon', 'Ireneo de Lyon', 'Esmirna, Imperio Romano', '140', '202', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Pedro Abelardo', 'Pedro Abelardo', 'Le Pallet, Francia', '1079', '1142', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Alejandro de Hales', 'Alejandro de Hales', 'Halesowen, Reino Unido', '1175', '1245', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Alberto Magno', 'San Alberto Magno', 'Lauingen, Baviera', '1200', '1280', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Juan Duns Scoto', 'Juan Duns Scoto', 'Duns, Reino de Escocia', '1266', '1308', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Buenaventura de Bagnoregio', 'Juan de Fidanza', 'Bagnoregio, Toscana, Sacro Imperio', '1217', '1274', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Francisco Suárez', 'Francisco Suárez Vázquez', 'Granada, Imperio español', '1548', '1617', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Amonio Saccas', 'Amonio Saccas', 'Alejandría, Imperio romano', '175', '242', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Jámblico de Calcis', 'Jámblico', 'Qinnasrin, Siria', '245', '325', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Proclo', 'Proclo', 'Constantinopla, Imperio bizantino', '412', '485', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Plutarco de Atenas', 'Plutarco', 'Atenas, Imperio bizantino', '350', '430', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Siriano de Alejandría', 'Siriano', ' Alejandría, Egipto', '380', '437', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Hipatia', 'Hipatia', 'Alejandría, Imperio romano', '355', '415', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Sinesio de Cirene', 'Sinesio', 'Cirene, Libia', '370', '413', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Meliso de Samos', 'Meliso', 'Isla de Samos, Antigua Grecia', '470 a.C.', '430 a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Zenón de Elea', 'Zenón', 'Elea, Magna Grecia (Italia)', '490 a.C.', '430 a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Christian Wolff', 'Christian von Wolff', 'Breslavia (Reino de Bohemia)', '1679', '1754', 'Era de la Razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Friedrich Engels', 'Friedrich Engels', 'Barmen, Reino de Prusia', '1820', '1895', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Gilles Deleuze', 'Gilles Deleuze', 'XVII Distrito de París, Francia', '1925', '1995', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Jacques Derrida', 'Jacques Derrida', 'El-Biar, Argelia francesa', '1930', '2004', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Martin Heidegger', 'Martin Heidegger', 'Messkirch, Imperio alemán', '1889', '1976', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('George Edward Moore', 'George Edward Moore', 'Upper Norwood, Londres', '1873', '1958', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Crates de Tebas', 'Crates', 'Tebas, Antigua Grecia', '365 a.C.', '285 a.C.', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Cleantes de Aso', 'Cleantes', 'Aso, Misia, Turquía', '331 a.C.', '232 a.C.', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Crisipo de Solos', 'Crisipo', 'Solos, Turquía', '281 a.C.', '208 a.C.', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Diógenes de Babilonia', 'Diógenes', 'Seleucia del Tigris, Imperio seléucida', '240 a.C.', '150 a.C.', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Antípatro de Tarso', 'Antípatro', 'Tarso, Turquía', 'Siglo III a.C.', '129 a.C.', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Panecio de Rodas', 'Panecio', 'Isla de Rodas, Antigua Grecia', '185 a.C.', '110 a.C.', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Posidonio', 'Posidonio', 'Apamea, Siria', '135 a.C.', '51 a.C.', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Filodemo de Gadara', 'Filodemo', 'Gadara, Jordania', '110 a.C.', '35 a.C.', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Diógenes de Enoanda', 'Diógenes', 'Enoanda, Licia, Turquía', '', 'Siglo II', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Metrodoro de Lámpsaco', 'Metrodoro', 'Lámpsaco, Turquía', '331 a.C.', '277 a.C.', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Hermarco de Mitilene', 'Hermarco', 'Mitilene, Antigua Grecia', '325 a.C.', '250 a.C.', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Polístrato el Epicúreo', 'Polístrato', '', 'Siglo III a.C.', '219 a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Leontion', 'Leontion', '', 'Siglo IV a.C', 'Siglo IV a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Colotes de Lámpsaco', 'Colotes', 'Lámpsaco, Turquía', '320 a.C.', '268 a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Apolodoro el Epicúreo', 'Apolodoro', '', 'Siglo II a.C.', '', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Zenón de Sidón', 'Zenón', 'Sidón, Líbano', '150 a.C.', '75 a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Lucrecio', 'Tito Lucrecio Caro', '', '99 a.C.', '55 a.C.', 'Presocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Ramon Llull', 'Ramon Llull', 'Ciudad de Mallorca, Corona de Aragón', '1232', '1315', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Arquímedes de Siracusa', 'Arquímedes', 'Siracusa, Sicilia, Magna Grecia', '287 a.C.', '212 a.C.', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Aristipo', 'Aristipo', 'Cirene, Libia', '435 a.C.', '350 a.C.', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Nicolás Oresme', 'Nicolás Oresme', 'Fleury-sur-Orne, Reino de Francia', '1323', '1382', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Auguste Comte', 'Isidore Marie Auguste François Xavier Comte', 'Montpellier, Primera República Francesa', '1798', '1857', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Siger de Brabant', 'Siger de Brabant', 'Ducado de Brabante, Sacro Imperio Romano Germánico', '1235', '1284', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Boecio de Dacia', 'Boecio de Dacia', 'Península de Jutlandia', 'Siglo III', '1284', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Jacques Lefèvre d´Étaples', 'Jacques Lefèvre d´Étaples', 'Étaples, Picardía, Reino de Francia)', '1450', '1536', 'Era de la Razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Paul Oskar Kristeller', 'Paul Oskar Kristeller', 'Berlín, Imperio alemán', '1905', '1999', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Michel de Montaigne', 'Michel Eyquem de Montaigne', 'Castillo de Montaigne, Francia', '1533', '1592', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Werner Wilhelm Jaeger', 'Werner Jaeger', 'Lobberich, Alemania', '1888', '1961', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Jacques Maritain', 'Jacques Maritain', 'París, Francia', '1882', '1973', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Erich Fromm', 'Erich Seligmann Fromm', 'Fráncfort del Meno, Hesse, Alemania', '1900', '1980', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Rodolfo Mondolfo', 'Rodolfo Mondolfo', 'Senigallia, Italia', '1877', '1976', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Johannes Kepler', 'Johannes Kepler', 'Weil der Stadt, Sacro Imperio Romano Germánico', '1571', '1630', 'Era de la Razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('John Herschel', 'John Frederick William Herschel', 'Slough, Buckinghamshire, Reino Unido', '1792', '1871', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Bernard Bolzano', 'Bernard Placidus Johann Gonzal Nepomuk Bolzano', 'Praga, Reino de Bohemia', '1781', '1848', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('William Whewell', 'William Whewell', 'Lancaster, Reino Unido', '1794', '1866', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('John Stuart Mill', 'John Stuart Mill', 'Londres, Reino Unido de Gran Bretaña e Irlanda', '1806', '1873', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Herbert Spencer', 'Herbert Spencer', 'Derby, Reino Unido de Gran Bretaña e Irlanda', '1820', '1903', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Pierre Duhem', 'Pierre Maurice Marie Duhem', 'II Distrito de París, Francia', '1861', '1916', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Ludwig Wittgenstein', 'Ludwig Josef Johann Wittgenstein', 'Viena, Imperio austrohúngaro', '1889', '1951', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Karl Popper', 'Karl Raimund Popper', 'Viena Imperio austrohúngaro', '1902', '1994', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Thomas Kuhn', 'Thomas Samuel Kuhn', 'Cincinnati, Ohio, Estados Unidos', '1922', '1996', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Paul Feyerabend', 'Paul Karl Feyerabend', 'Viena, Primera República de Austria', '1924', '1994', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Imre Lakatos', 'Imre Lakatos', 'Debrecen, Hungría', '1922', '1974', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('George Berkeley', 'George Berkeley', 'Kilkenny, Irlanda', '1685', '1753', 'Era de la Razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Johann Gottlieb Fichte', 'Johann Gottlieb Fichte', 'Rammenau, Sacro Imperio Romano Germánico', '1762', '1814', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Friedrich Schelling', 'Friedrich Wilhelm Joseph (von) Schelling', 'Leonberg, Alemania', '1775', '1854', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Francis Herbert Bradley', 'Francis Herbert Bradley', 'Clapham, Reino Unido', '1846', '1924', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Giovanni Gentile', 'Giovanni Gentile', 'Castelvetrano, Italia', '1875', '1944', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Wilhelm Dilthey', 'Wilhelm Dilthey', 'Wiesbaden-Biebrich, Confederación Germánica', '1833', '1911', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Ernst Mach', 'Ernst Mach', 'Brno-Chrlice, República Checa', '1838', '1916', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Ernst Cassirer', 'Ernst Alfred Cassirer', 'Breslau, Silesia, Prusia, Imperio alemán', '1874', '1945', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Robin George Collingwood', 'Robin George Collingwood', 'Cartmel Fell, Reino Unido', '1889', '1943', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Friedrich Heinrich Jacobi', 'Friedrich Heinrich Jacobi', 'Düsseldorf, Alemania', '1743', '1819', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Gottlob Ernst Schulze', 'Gottlob Ernst Schulze', 'Heldrungen, Turingia', '1761', '1833', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Karl Leonhard Reinhold', 'Karl Leonhard Reinhold', 'Viena, Imperio Habsburgo', '1757', '1823', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Friedrich Schleiermacher', 'Friedrich Daniel Ernst Schleiermacher', 'Breslavia, Silesia, Reino de Prusia', '1768', '1834', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Rudolf Hermann Lotze', 'Rudolf Hermann Lotze', 'Bautzen, Alemania', '1817', '1881', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Gustav Fechner', 'Gustav Theodor Fechner', 'Zarki Wielkie, Polonia', '1801', '1887', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Hermann Cohen', 'Hermann Cohen', 'Coswig, Sajonia-Anhalt, Alemania', '1842', '1918', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Paul Natorp', 'Paul Gerhard Natorp', 'Düsseldorf, Alemania', '1854', '1924', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Nicolai Hartmann', 'Nicolai Hartmann', 'Riga, Imperio ruso', '1882', '1950', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Wilhelm Windelband', 'Wilhelm Windelband', 'Potsdam, Reino de Prusia', '1848', '1915', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Alois Riehl', 'Alois Adolf Riehl', 'Bolzano, Imperio austríaco', '1844', '1924', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Georg Simmel', 'Georg Simmel', 'Berlín, Alemania', '1858', '1918', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Max Scheler', 'Max Scheler', 'Múnich, Imperio alemán', '1874', '1927', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Rudolf Stammler', 'Karl Eduard Julius Theodor Rudolf Stammler', 'Alsfeld, Gran ducado de Hessen y del Rin', '1856', '1938', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Friedrich Albert Lange', 'Friedrich Albert Lange', 'Wald, Alemania', '1828', '1875', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Heinrich Rickert', 'Heinrich Rickert', 'Gdansk, Reino de Prusia', '1863', '1936', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Søren Kierkegaard', 'Søren Aabye Kierkegaard', 'Copenhague, Reino de Dinamarca y Noruega', '1813', '1855', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Blaise Pascal', 'Blaise Pascal', 'Clermont-Ferrand, Auvernia, Francia', '1623', '1662', 'Era de la Razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Fiódor Dostoyevski', 'Fiódor Mijáilovich Dostoyevski', 'Moscú, Imperio ruso', '1821', '1881', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Lev Shestov', 'Lev Isaákovich Shestov', 'Kiev, Imperio ruso', '1866', '1938', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Gabriel Marcel', 'Gabriel Marcel', 'París, Francia', '1889', '1973', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Karl Jaspers', 'Karl Theodor Jaspers', 'Oldemburgo, Alemania', '1883', '1969', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Albert Camus', 'Albert Camus', 'Mondovi, Argelia francesa', '1913', '1960', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Simone de Beauvoir', 'Simone Lucie Ernestine Marie Bertrand de Beauvoir', 'París, Francia', '1908', '1986', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Walter Kaufmann', 'Walter Arnold Kaufmann', 'Friburgo de Brisgovia, República de Weimar', '1921', '1980', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Miguel de Unamuno', 'Miguel de Unamuno y Jugo', 'Bilbao, España', '1864', '1936', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Frederik Buytendijk', 'Frederic Jacobus Johannes Buytendijk', 'Breda, Países Bajos', '1887', '1974', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Edmund Husserl', 'Edmund Gustav Albrecht Husserl', 'Prostejov, Moravia', '1859', '1938', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Martin Buber', 'Martin Buber', 'Jerusalén, Israel', '1878', '1965', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Nicola Abbagnano', 'Nicola Abbagnano', 'Salerno, Italia', '1901', '1990', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Nikolái Berdiáyev', 'Nikolái Aleksándrovich Berdiáyev', 'Kiev, Imperio ruso', '1874', '1948', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Peter Wessel Zapffe', 'Peter Wessel Zapffe', 'Tromsø, Noruega', '1899', '1990', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Simone Weil', 'Simone Weil', 'París, Francia', '1909', '1943', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Viktor Frankl', 'Viktor Emil Frankl', 'Viena, Imperio austrohúngaro', '1905', '1997', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Paulo Freire', 'Paulo Reglus Neves Freire', 'Recife, Brasil', '1921', '1997', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Emmanuel Mounier', 'Emmanuel Mounier', 'Grenoble, Francia', '1905', '1950', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Paul Draper', 'Paul Robert Draper', 'Estados Unidos', '1957', '', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Michael Martin', 'Michael Lou Martin', 'Cincinnati, Estados Unidos', '1932', '2015', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('William Leonard Rowe', 'William Leonard Rowe', 'Lafayette, Estados Unidos', '1931', '2015', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Ludwig Feuerbach', 'Ludwig Andreas Feuerbach', 'Landshut, Baviera', '1804', '1872', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Mijaíl Bakunin', 'Mijaíl Aleksándrovich Bakunin', 'Priamukhino, Rusia', '1814', '1876', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Sigmund Freud', 'Sigmund Freud', 'Freiberg in Mähren, Moravia, Imperio austríaco', '1856', '1939', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Daniel Dennett', 'Daniel Clement Dennett', 'Boston, Massachusetts, Estados Unidos', '1942', '', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Sam Harris', 'Samuel Benjamin Harris', 'Estados Unidos', '1967', '', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Graham Oppy', 'Graham Robert Oppy', 'Benalla, Australia', '1960', '', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Diágoras de Melos', 'Diágoras de Melos', 'Melos, Antigua Grecia', '465 a.C.', '410 a.C.', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Teodoro el Ateo', 'Teodoro', 'Cirene, Antigua Grecia', '340 a.C.', '250 a.C.', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Estratón de Lámpsaco', 'Estratón', 'Lámpsaco, Turquía', '335 a.C.', '269 a.C.', 'Postsocraticos');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Sexto Empírico', 'Sexto Empírico', '', '160', '210', 'Imperio Romano');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Al-Razi', 'Al-Razi', 'Rayy, Irán', '865', '925', 'Edad media');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Casimir Liszinski', 'Kazimierz Lyszczynski', 'Lyszczyce, Bielorrusia', '1634', '1689', 'Filósofos de la razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Jean Meslier', 'Jean Meslier', 'Mazerny, Francia', '1664', '1729', 'Filósofos de la razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Paul Henri Thiry d´Holbach', 'Paul Heinrich Dietrich von Holbach', 'Edesheim, Alemania', '1723', '1789', 'Filósofos de la razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Jacques-André Naigeon', 'Jacques-André Naigeon', 'París, Reino de Francia', '1738', '1810', 'Filósofos de la razón');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Max Stirner', 'Johann Kaspar Schmidt', 'Bayreuth, Confederación del Rin', '1806', '1856', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Mao Zedong', 'Mao Zedong', 'Shaoshan, Hunan, China', '1893', '1976', 'Filósofos del siglo XX');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Vladímir Lenin', 'Vladímir Ilich Uliánov', 'Simbirsk, Imperio ruso', '1870', '1924', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Hippolyte Taine', 'Hippolyte Adolphe Taine', 'Vouziers, Francia', '1828', '1893', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('Jean-Marie Guyau', 'Jean-Marie Guyau Tuillerie', 'Laval, Mayenne, Francia', '1854', '1888', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte, periodo) values('James Mill', 'James Mill', 'Angus, Reino de Gran Bretaña', '1773', '1836', 'Filósofos de la Revolución');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Jeremy Bentham', 'Jeremy Bentham', 'Houndsditch, Reino de Gran Bretaña', '1748', '1832');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Charles Darwin', 'Charles Robert Darwin', 'Shrewsbury, Reino Unido de Gran Bretaña e Irlanda', '1809', '1882');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Roberto Ardigò', 'Roberto Felice Ardigò', 'Casteldidone, Italia', '1828', '1920');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Karl Eugen Dühring', 'Karl Eugen Dühring', 'Berlín, Alemania', '1833', '1921');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Ernst Laas', 'Ernst Laas', 'Fürstenwalde, Alemania', '1837', '1885');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Richard Avenarius', 'Richard Heinrich Ludwig Avenarius', 'París, Francia', '1843', '1896');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Hans Vaihinger', 'Hans Vaihinger', 'Nehren, Alemania', '1852', '1933');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Theodor Ziehen', 'Georg Theodor Ziehen', 'Fráncfort del Meno, Alemania', '1862', '1950');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Henri de Saint-Simon', 'Claude-Henri de Rouvroy, conde de Saint-Simon', 'París, Francia', '1760', '1825');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Émile Littré', 'Émile Maximilien Paul Littré', 'París, Primera República Francesa', '1801', '1881');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Jorge Lagarrigue', 'Jorge Lagarrigue Alessandri', 'Santiago de Chile, Chile', '1854', '1894');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Samuel Taylor Coleridge', 'Samuel Taylor Coleridge', 'Ottery St. Mary, Devon, Inglaterra', '1772', '1834');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Hegesías de Cirene', 'Hegesías', 'Cirene, Libia', 'Siglo IV a.C.', 'Siglo IV a.C.');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Philipp Mainländer', 'Philipp Mainländer', 'Offenbach del Meno, Alemania', '1841', '1876');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Eduard von Hartmann', 'Karl Robert Eduard von Hartmann', 'Berlín, Reino de Prusia', '1842', '1906');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Giacomo Leopardi', 'Giacomo Leopardi', 'Recanati, Estados Pontificios', '1798', '1837');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Thomas Hardy', 'Thomas Hardy', 'Dorchester, Reino Unido', '1840', '1928');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Emil Cioran', 'Emil Cioran', 'Rasinari, Transilvania, Imperio austrohúngaro', '1911', '1995');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Albert Caraco', 'Albert Caraco', 'Constantinopla, Imperio otomano', '1919', '1971');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('William Godwin', 'William Godwin', 'Cambridgeshire, Wisbech', '1756', '1836');
insert into filosofos(nombre_reconocido, nombre, ciudad, anio, muerte) values('Henry Sidgwick', 'Henry Sidgwick', 'Skipton, Reino Unido', '1838', '1900');

